---

- name: install basic docker environment
  hosts: all
  gather_facts: true
  vars_files:
    - vars.yml
  roles:
    - basic
    - docker
    - docker-compose
    - userconf
    - swap
    - services
